# Generated by Django 3.2.9 on 2022-03-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('job', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('email_address', models.EmailField(blank=True, max_length=50)),
                ('phone', models.CharField(default='N/A', max_length=20)),
                ('mobile', models.CharField(default='N/A', max_length=200)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(default='default/avatar.png', upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
