# Generated by Django 3.2.9 on 2022-03-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_devmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devmember',
            name='avatar',
            field=models.ImageField(default='default/avatar.png', upload_to='dev_profile/'),
        ),
    ]
