# Generated by Django 3.2.9 on 2022-03-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_devmember_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devmember',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
