# Generated by Django 3.2.9 on 2022-03-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_devmember_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DevMember',
        ),
    ]
