# Generated by Django 3.2.9 on 2022-03-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20220309_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devprofessionalvolunteerexp',
            name='inclusive_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='devtrainingsseminarsworkshopattended',
            name='inclusive_date',
            field=models.DateField(),
        ),
    ]
