# Generated by Django 3.2.9 on 2022-03-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20220309_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devedubackground',
            old_name='training_seminar_workshop_attended',
            new_name='school_or_institution',
        ),
    ]
