# Generated by Django 3.2.9 on 2022-03-13 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0010_rename_training_seminar_workshop_attended_devedubackground_school_or_institution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devedubackground',
            options={'ordering': ['-created_at'], 'verbose_name': 'Educational Background', 'verbose_name_plural': 'Educational Backgrounds'},
        ),
        migrations.AlterModelOptions(
            name='devprofessionalvolunteerexp',
            options={'ordering': ['-created_at'], 'verbose_name': 'Professional/Volunteer Experience', 'verbose_name_plural': 'Professional/Volunteer Experiences'},
        ),
        migrations.AlterModelOptions(
            name='devtrainingsseminarsworkshopattended',
            options={'ordering': ['-created_at'], 'verbose_name': 'Trainings, Seminars/Workshop Attended', 'verbose_name_plural': 'Trainings, Seminars/Workshop Attended'},
        ),
        migrations.CreateModel(
            name='MessageToAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_message', models.TextField(max_length=500)),
                ('message_reply', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Messages',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
