# Generated by Django 3.2.9 on 2022-03-13 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20220313_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetoauthor',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.profile'),
        ),
    ]
