# Generated by Django 3.2.9 on 2022-03-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_messagetoauthor_sender_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageToAuthor',
        ),
    ]
