# Generated by Django 3.2.9 on 2022-03-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_devlanguages_devskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
